name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:

  build:

    runs-on: self-hosted

    steps:
    - name: Pull Docker image
      run: sudo docker pull 0yash4/pishing-domain-detection:latest
    - name: Delete Old docker container
      run: sudo docker rm -f pishing-domain-detection || true
    - name: Run Docker Container
      run: sudo  docker run -p 8501:8501 pishing-domain-detection 0yash4/pishing-domain-detection:latest