name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  build:
    runs-on: self-hosted
    if: ${{ github.event.workflow_run.conclusion == 'success' }}  # Ensures CD only runs if CI succeeds

    steps:
    - name: Free up disk space by removing unused Docker resources
      run: |
        sudo docker stop $(sudo docker ps -aq) || true
        sudo docker rm -f $(sudo docker ps -aq) || true
        sudo docker system prune -a -f --volumes

    - name: Pull Docker image
      run: sudo docker pull 0yash4/fastapi_pishing_domain:latest

    - name: Delete Old Docker Container (if exists)
      run: sudo docker rm -f fastapi_pishing_domain || true

    - name: Run Docker Container
      run: sudo docker run -d --name fastapi_pishing_domain -p 8000:8000 0yash4/fastapi_pishing_domain:latest

#everything should work now