name: CI Pipeline
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASS }}
    
    - name: Install dos2unix
      run: sudo apt-get install -y dos2unix

    - name: Check if model.pkl exists
      run: |
        if [ -f model.pkl ]; then
          echo "model.pkl found!"
        else
          echo "ERROR: model.pkl not found!"
          exit 1
        fi

    - name: Convert line endings for model.pkl
      if: hashFiles('model.pkl') != ''
      run: dos2unix model.pkl

    - name: Build the Docker image
      run: sudo docker build -t 0yash4/fastapi_pishing_domain:latest .

    - name: Push to Docker Hub
      run: sudo docker push 0yash4/fastapi_pishing_domain:latest

    - name: Deleting all the Docker images available in the system
      run: sudo docker rmi -f $(sudo docker images -aq)

