name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Login Docker
      env:
          DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
          DOCKER_PASS: ${{secrets.DOCKER_PASS}}
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASS
    - name: Build the Docker image
      run: docker build -t pishing-domain-detection
    - name: Push to Docker hub
      run: docker push 0yash4/pishing-domain-detection:latest
      
